# version: '3.8'

# services:
#   postgres:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: webhook_service_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data  # Persisting data
#     networks:
#       - app_network

#   fastapi:
#     build: .
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - postgres
#     environment:
#       DB_HOST: postgres
#       DB_PORT: 5432
#       DB_USER: user
#       DB_PASSWORD: password
#       DB_NAME: webhook_service_db
#     networks:
#       - app_network

# networks:
#   app_network:
#     driver: bridge

# volumes:
#   postgres_data:  # Volume definition for persisting Postgres data
version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webhook_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app_network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: webhook_service_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    networks:
      - app_network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.worker worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: webhook_service_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    networks:
      - app_network

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.main beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
      - celery_worker
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: webhook_service_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: